<?php
  class ImageCollection {

    /**
     * @param string $url
     */
    public function __construct($url)
    {
      $html = \SimpleHtmlDom\file_get_html($url);
      $this->siteUrl = $url;
      $this->siteTitle = $html->find('title', 0)->plaintext;
      $this->images = $this->buildArray($html, $url);
    }

    /**
     * Array Builder
     *
     * Iterate through each of the images scraped from the HTML page and create
     * an array if Image objects
     *
     * @param object $html Object generated by SimpleHtmlDom
     * @return array
     */
    private function buildArray($html, $url)
    {
      $images = array();
      $unique = array_unique($html->find('img'));
      foreach($unique as $result){
        $img = new Image($result, $url);
        array_push($images, $img);
      }
      return $images;
    }

  }