<?php
  class ImageCollection {

    /**
     * @param $url
     */
    public function __construct($url)
    {
      if(filter_var($url, FILTER_VALIDATE_URL)){
        $html = \SimpleHtmlDom\file_get_html($url);
        $this->siteUrl = $url;
        $this->siteTitle = $html->find('title', 0)->plaintext;
        $this->images = $this->buildArray($html);
      } else {
        $this->exceptionHandler($url);
      }
    }

    /**
     * Array Builder
     *
     * Iterate through each of the images scraped from the HTML page and create
     * an array if Image objects
     *
     * @param object $html Object generated by SimpleHtmlDom
     * @return array
     */
    private function buildArray($html)
    {
      $images = array();
      $unique = array_unique($html->find('img'));
      foreach($unique as $result){
        $img = new Image($result);
        array_push($images, $img);
      }
      return $images;
    }

    /**
     * @param $url
     * @throws Exception
     */
    private function exceptionHandler($url)
    {
      if ($url == '') {
        throw new Exception('No URL given');
      } else {
        throw new Exception($url . ' is not a valid URL');
      }
    }

  }